export function toReview(row: Record<string, unknown>) {
  return {
    id: row.id,
    title: row.title,
    brandName: row.brand_name,
    productName: row.product_name,
    price: row.price,
    imageUrl: row.image_url,
    images: row.images ?? [],
    episode: row.episode,
    likes: row.likes ?? 0,
    wantCount: row.want_count ?? 0,
    giftCount: row.gift_count ?? 0,
    gender: row.gender,
    ageGroup: row.age_group,
    relationship: row.relationship ?? [],
    scene: row.scene ?? [],
    category: row.category ?? [],
    authorId: row.user_id,
    authorName: row.author_name,
    authorIcon: row.author_icon,
    createdAt: row.created_at,
    productUrl: row.product_url,
    amazonUrl: row.amazon_url,
    rakutenUrl: row.rakuten_url,
    rakutenImageUrl: row.rakuten_image_url,
    rakutenItemName: row.rakuten_item_name,
    rakutenItemPrice: row.rakuten_item_price,
    referencePrice: row.reference_price,
    status: row.status,
  };
}
